<template>
  <span>Title</span>
  <nav>
    <ul>
      <li>Dashboard</li>
      <li>Dashboard</li>
      <li>Dashboard</li>
      <li>Dashboard</li>
      <li>Dashboard</li>
      <li>Dashboard</li>
    </ul>
  </nav>
</template>
